// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/common/clients/auth/models"
)

// GetCurrentUserReader is a Reader for the GetCurrentUser structure.
type GetCurrentUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCurrentUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetCurrentUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetCurrentUserUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCurrentUserInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /me] GetCurrentUser", response, response.Code())
	}
}

// NewGetCurrentUserOK creates a GetCurrentUserOK with default headers values
func NewGetCurrentUserOK() *GetCurrentUserOK {
	return &GetCurrentUserOK{}
}

/*
GetCurrentUserOK describes a response with status code 200, with default header values.

OK
*/
type GetCurrentUserOK struct {
	Payload *models.APIUserResponse
}

// IsSuccess returns true when this get current user o k response has a 2xx status code
func (o *GetCurrentUserOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get current user o k response has a 3xx status code
func (o *GetCurrentUserOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get current user o k response has a 4xx status code
func (o *GetCurrentUserOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get current user o k response has a 5xx status code
func (o *GetCurrentUserOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get current user o k response a status code equal to that given
func (o *GetCurrentUserOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get current user o k response
func (o *GetCurrentUserOK) Code() int {
	return 200
}

func (o *GetCurrentUserOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /me][%d] getCurrentUserOK %s", 200, payload)
}

func (o *GetCurrentUserOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /me][%d] getCurrentUserOK %s", 200, payload)
}

func (o *GetCurrentUserOK) GetPayload() *models.APIUserResponse {
	return o.Payload
}

func (o *GetCurrentUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIUserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCurrentUserUnauthorized creates a GetCurrentUserUnauthorized with default headers values
func NewGetCurrentUserUnauthorized() *GetCurrentUserUnauthorized {
	return &GetCurrentUserUnauthorized{}
}

/*
GetCurrentUserUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetCurrentUserUnauthorized struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this get current user unauthorized response has a 2xx status code
func (o *GetCurrentUserUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get current user unauthorized response has a 3xx status code
func (o *GetCurrentUserUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get current user unauthorized response has a 4xx status code
func (o *GetCurrentUserUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get current user unauthorized response has a 5xx status code
func (o *GetCurrentUserUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get current user unauthorized response a status code equal to that given
func (o *GetCurrentUserUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get current user unauthorized response
func (o *GetCurrentUserUnauthorized) Code() int {
	return 401
}

func (o *GetCurrentUserUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /me][%d] getCurrentUserUnauthorized %s", 401, payload)
}

func (o *GetCurrentUserUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /me][%d] getCurrentUserUnauthorized %s", 401, payload)
}

func (o *GetCurrentUserUnauthorized) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *GetCurrentUserUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCurrentUserInternalServerError creates a GetCurrentUserInternalServerError with default headers values
func NewGetCurrentUserInternalServerError() *GetCurrentUserInternalServerError {
	return &GetCurrentUserInternalServerError{}
}

/*
GetCurrentUserInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetCurrentUserInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this get current user internal server error response has a 2xx status code
func (o *GetCurrentUserInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get current user internal server error response has a 3xx status code
func (o *GetCurrentUserInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get current user internal server error response has a 4xx status code
func (o *GetCurrentUserInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get current user internal server error response has a 5xx status code
func (o *GetCurrentUserInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get current user internal server error response a status code equal to that given
func (o *GetCurrentUserInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get current user internal server error response
func (o *GetCurrentUserInternalServerError) Code() int {
	return 500
}

func (o *GetCurrentUserInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /me][%d] getCurrentUserInternalServerError %s", 500, payload)
}

func (o *GetCurrentUserInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /me][%d] getCurrentUserInternalServerError %s", 500, payload)
}

func (o *GetCurrentUserInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *GetCurrentUserInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
