// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/common/clients/auth/models"
)

// LoginReader is a Reader for the Login structure.
type LoginReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LoginReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewLoginOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewLoginBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewLoginUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewLoginInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /login] Login", response, response.Code())
	}
}

// NewLoginOK creates a LoginOK with default headers values
func NewLoginOK() *LoginOK {
	return &LoginOK{}
}

/*
LoginOK describes a response with status code 200, with default header values.

OK
*/
type LoginOK struct {
	Payload *models.APITokenResponse
}

// IsSuccess returns true when this login o k response has a 2xx status code
func (o *LoginOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this login o k response has a 3xx status code
func (o *LoginOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this login o k response has a 4xx status code
func (o *LoginOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this login o k response has a 5xx status code
func (o *LoginOK) IsServerError() bool {
	return false
}

// IsCode returns true when this login o k response a status code equal to that given
func (o *LoginOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the login o k response
func (o *LoginOK) Code() int {
	return 200
}

func (o *LoginOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /login][%d] loginOK %s", 200, payload)
}

func (o *LoginOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /login][%d] loginOK %s", 200, payload)
}

func (o *LoginOK) GetPayload() *models.APITokenResponse {
	return o.Payload
}

func (o *LoginOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APITokenResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewLoginBadRequest creates a LoginBadRequest with default headers values
func NewLoginBadRequest() *LoginBadRequest {
	return &LoginBadRequest{}
}

/*
LoginBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type LoginBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this login bad request response has a 2xx status code
func (o *LoginBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this login bad request response has a 3xx status code
func (o *LoginBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this login bad request response has a 4xx status code
func (o *LoginBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this login bad request response has a 5xx status code
func (o *LoginBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this login bad request response a status code equal to that given
func (o *LoginBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the login bad request response
func (o *LoginBadRequest) Code() int {
	return 400
}

func (o *LoginBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /login][%d] loginBadRequest %s", 400, payload)
}

func (o *LoginBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /login][%d] loginBadRequest %s", 400, payload)
}

func (o *LoginBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *LoginBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewLoginUnauthorized creates a LoginUnauthorized with default headers values
func NewLoginUnauthorized() *LoginUnauthorized {
	return &LoginUnauthorized{}
}

/*
LoginUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type LoginUnauthorized struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this login unauthorized response has a 2xx status code
func (o *LoginUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this login unauthorized response has a 3xx status code
func (o *LoginUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this login unauthorized response has a 4xx status code
func (o *LoginUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this login unauthorized response has a 5xx status code
func (o *LoginUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this login unauthorized response a status code equal to that given
func (o *LoginUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the login unauthorized response
func (o *LoginUnauthorized) Code() int {
	return 401
}

func (o *LoginUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /login][%d] loginUnauthorized %s", 401, payload)
}

func (o *LoginUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /login][%d] loginUnauthorized %s", 401, payload)
}

func (o *LoginUnauthorized) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *LoginUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewLoginInternalServerError creates a LoginInternalServerError with default headers values
func NewLoginInternalServerError() *LoginInternalServerError {
	return &LoginInternalServerError{}
}

/*
LoginInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type LoginInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this login internal server error response has a 2xx status code
func (o *LoginInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this login internal server error response has a 3xx status code
func (o *LoginInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this login internal server error response has a 4xx status code
func (o *LoginInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this login internal server error response has a 5xx status code
func (o *LoginInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this login internal server error response a status code equal to that given
func (o *LoginInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the login internal server error response
func (o *LoginInternalServerError) Code() int {
	return 500
}

func (o *LoginInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /login][%d] loginInternalServerError %s", 500, payload)
}

func (o *LoginInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /login][%d] loginInternalServerError %s", 500, payload)
}

func (o *LoginInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *LoginInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
