// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/PRPO-skupina-02/common/clients/auth/models"
)

// RefreshTokenReader is a Reader for the RefreshToken structure.
type RefreshTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RefreshTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewRefreshTokenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRefreshTokenBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewRefreshTokenUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRefreshTokenInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /refresh] RefreshToken", response, response.Code())
	}
}

// NewRefreshTokenOK creates a RefreshTokenOK with default headers values
func NewRefreshTokenOK() *RefreshTokenOK {
	return &RefreshTokenOK{}
}

/*
RefreshTokenOK describes a response with status code 200, with default header values.

OK
*/
type RefreshTokenOK struct {
	Payload *models.APITokenResponse
}

// IsSuccess returns true when this refresh token o k response has a 2xx status code
func (o *RefreshTokenOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this refresh token o k response has a 3xx status code
func (o *RefreshTokenOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this refresh token o k response has a 4xx status code
func (o *RefreshTokenOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this refresh token o k response has a 5xx status code
func (o *RefreshTokenOK) IsServerError() bool {
	return false
}

// IsCode returns true when this refresh token o k response a status code equal to that given
func (o *RefreshTokenOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the refresh token o k response
func (o *RefreshTokenOK) Code() int {
	return 200
}

func (o *RefreshTokenOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /refresh][%d] refreshTokenOK %s", 200, payload)
}

func (o *RefreshTokenOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /refresh][%d] refreshTokenOK %s", 200, payload)
}

func (o *RefreshTokenOK) GetPayload() *models.APITokenResponse {
	return o.Payload
}

func (o *RefreshTokenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APITokenResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRefreshTokenBadRequest creates a RefreshTokenBadRequest with default headers values
func NewRefreshTokenBadRequest() *RefreshTokenBadRequest {
	return &RefreshTokenBadRequest{}
}

/*
RefreshTokenBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type RefreshTokenBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this refresh token bad request response has a 2xx status code
func (o *RefreshTokenBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this refresh token bad request response has a 3xx status code
func (o *RefreshTokenBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this refresh token bad request response has a 4xx status code
func (o *RefreshTokenBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this refresh token bad request response has a 5xx status code
func (o *RefreshTokenBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this refresh token bad request response a status code equal to that given
func (o *RefreshTokenBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the refresh token bad request response
func (o *RefreshTokenBadRequest) Code() int {
	return 400
}

func (o *RefreshTokenBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /refresh][%d] refreshTokenBadRequest %s", 400, payload)
}

func (o *RefreshTokenBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /refresh][%d] refreshTokenBadRequest %s", 400, payload)
}

func (o *RefreshTokenBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RefreshTokenBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRefreshTokenUnauthorized creates a RefreshTokenUnauthorized with default headers values
func NewRefreshTokenUnauthorized() *RefreshTokenUnauthorized {
	return &RefreshTokenUnauthorized{}
}

/*
RefreshTokenUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type RefreshTokenUnauthorized struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this refresh token unauthorized response has a 2xx status code
func (o *RefreshTokenUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this refresh token unauthorized response has a 3xx status code
func (o *RefreshTokenUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this refresh token unauthorized response has a 4xx status code
func (o *RefreshTokenUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this refresh token unauthorized response has a 5xx status code
func (o *RefreshTokenUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this refresh token unauthorized response a status code equal to that given
func (o *RefreshTokenUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the refresh token unauthorized response
func (o *RefreshTokenUnauthorized) Code() int {
	return 401
}

func (o *RefreshTokenUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /refresh][%d] refreshTokenUnauthorized %s", 401, payload)
}

func (o *RefreshTokenUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /refresh][%d] refreshTokenUnauthorized %s", 401, payload)
}

func (o *RefreshTokenUnauthorized) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RefreshTokenUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRefreshTokenInternalServerError creates a RefreshTokenInternalServerError with default headers values
func NewRefreshTokenInternalServerError() *RefreshTokenInternalServerError {
	return &RefreshTokenInternalServerError{}
}

/*
RefreshTokenInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type RefreshTokenInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this refresh token internal server error response has a 2xx status code
func (o *RefreshTokenInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this refresh token internal server error response has a 3xx status code
func (o *RefreshTokenInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this refresh token internal server error response has a 4xx status code
func (o *RefreshTokenInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this refresh token internal server error response has a 5xx status code
func (o *RefreshTokenInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this refresh token internal server error response a status code equal to that given
func (o *RefreshTokenInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the refresh token internal server error response
func (o *RefreshTokenInternalServerError) Code() int {
	return 500
}

func (o *RefreshTokenInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /refresh][%d] refreshTokenInternalServerError %s", 500, payload)
}

func (o *RefreshTokenInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /refresh][%d] refreshTokenInternalServerError %s", 500, payload)
}

func (o *RefreshTokenInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RefreshTokenInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
RefreshTokenBody refresh token body
swagger:model RefreshTokenBody
*/
type RefreshTokenBody struct {

	// refresh token
	RefreshToken string `json:"refresh_token,omitempty"`
}

// Validate validates this refresh token body
func (o *RefreshTokenBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this refresh token body based on context it is used
func (o *RefreshTokenBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *RefreshTokenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RefreshTokenBody) UnmarshalBinary(b []byte) error {
	var res RefreshTokenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
