// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/common/clients/auth/models"
)

// RegisterReader is a Reader for the Register structure.
type RegisterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RegisterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewRegisterCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRegisterBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewRegisterConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRegisterInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /register] Register", response, response.Code())
	}
}

// NewRegisterCreated creates a RegisterCreated with default headers values
func NewRegisterCreated() *RegisterCreated {
	return &RegisterCreated{}
}

/*
RegisterCreated describes a response with status code 201, with default header values.

Created
*/
type RegisterCreated struct {
	Payload *models.APIUserResponse
}

// IsSuccess returns true when this register created response has a 2xx status code
func (o *RegisterCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this register created response has a 3xx status code
func (o *RegisterCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this register created response has a 4xx status code
func (o *RegisterCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this register created response has a 5xx status code
func (o *RegisterCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this register created response a status code equal to that given
func (o *RegisterCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the register created response
func (o *RegisterCreated) Code() int {
	return 201
}

func (o *RegisterCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /register][%d] registerCreated %s", 201, payload)
}

func (o *RegisterCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /register][%d] registerCreated %s", 201, payload)
}

func (o *RegisterCreated) GetPayload() *models.APIUserResponse {
	return o.Payload
}

func (o *RegisterCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIUserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRegisterBadRequest creates a RegisterBadRequest with default headers values
func NewRegisterBadRequest() *RegisterBadRequest {
	return &RegisterBadRequest{}
}

/*
RegisterBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type RegisterBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this register bad request response has a 2xx status code
func (o *RegisterBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this register bad request response has a 3xx status code
func (o *RegisterBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this register bad request response has a 4xx status code
func (o *RegisterBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this register bad request response has a 5xx status code
func (o *RegisterBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this register bad request response a status code equal to that given
func (o *RegisterBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the register bad request response
func (o *RegisterBadRequest) Code() int {
	return 400
}

func (o *RegisterBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /register][%d] registerBadRequest %s", 400, payload)
}

func (o *RegisterBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /register][%d] registerBadRequest %s", 400, payload)
}

func (o *RegisterBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RegisterBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRegisterConflict creates a RegisterConflict with default headers values
func NewRegisterConflict() *RegisterConflict {
	return &RegisterConflict{}
}

/*
RegisterConflict describes a response with status code 409, with default header values.

Conflict
*/
type RegisterConflict struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this register conflict response has a 2xx status code
func (o *RegisterConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this register conflict response has a 3xx status code
func (o *RegisterConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this register conflict response has a 4xx status code
func (o *RegisterConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this register conflict response has a 5xx status code
func (o *RegisterConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this register conflict response a status code equal to that given
func (o *RegisterConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the register conflict response
func (o *RegisterConflict) Code() int {
	return 409
}

func (o *RegisterConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /register][%d] registerConflict %s", 409, payload)
}

func (o *RegisterConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /register][%d] registerConflict %s", 409, payload)
}

func (o *RegisterConflict) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RegisterConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRegisterInternalServerError creates a RegisterInternalServerError with default headers values
func NewRegisterInternalServerError() *RegisterInternalServerError {
	return &RegisterInternalServerError{}
}

/*
RegisterInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type RegisterInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this register internal server error response has a 2xx status code
func (o *RegisterInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this register internal server error response has a 3xx status code
func (o *RegisterInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this register internal server error response has a 4xx status code
func (o *RegisterInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this register internal server error response has a 5xx status code
func (o *RegisterInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this register internal server error response a status code equal to that given
func (o *RegisterInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the register internal server error response
func (o *RegisterInternalServerError) Code() int {
	return 500
}

func (o *RegisterInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /register][%d] registerInternalServerError %s", 500, payload)
}

func (o *RegisterInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /register][%d] registerInternalServerError %s", 500, payload)
}

func (o *RegisterInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *RegisterInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
