// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewVerifyTokenParams creates a new VerifyTokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVerifyTokenParams() *VerifyTokenParams {
	return &VerifyTokenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewVerifyTokenParamsWithTimeout creates a new VerifyTokenParams object
// with the ability to set a timeout on a request.
func NewVerifyTokenParamsWithTimeout(timeout time.Duration) *VerifyTokenParams {
	return &VerifyTokenParams{
		timeout: timeout,
	}
}

// NewVerifyTokenParamsWithContext creates a new VerifyTokenParams object
// with the ability to set a context for a request.
func NewVerifyTokenParamsWithContext(ctx context.Context) *VerifyTokenParams {
	return &VerifyTokenParams{
		Context: ctx,
	}
}

// NewVerifyTokenParamsWithHTTPClient creates a new VerifyTokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewVerifyTokenParamsWithHTTPClient(client *http.Client) *VerifyTokenParams {
	return &VerifyTokenParams{
		HTTPClient: client,
	}
}

/*
VerifyTokenParams contains all the parameters to send to the API endpoint

	for the verify token operation.

	Typically these are written to a http.Request.
*/
type VerifyTokenParams struct {

	/* Token.

	   Token to verify
	*/
	Token VerifyTokenBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the verify token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VerifyTokenParams) WithDefaults() *VerifyTokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the verify token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VerifyTokenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the verify token params
func (o *VerifyTokenParams) WithTimeout(timeout time.Duration) *VerifyTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the verify token params
func (o *VerifyTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the verify token params
func (o *VerifyTokenParams) WithContext(ctx context.Context) *VerifyTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the verify token params
func (o *VerifyTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the verify token params
func (o *VerifyTokenParams) WithHTTPClient(client *http.Client) *VerifyTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the verify token params
func (o *VerifyTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithToken adds the token to the verify token params
func (o *VerifyTokenParams) WithToken(token VerifyTokenBody) *VerifyTokenParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the verify token params
func (o *VerifyTokenParams) SetToken(token VerifyTokenBody) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *VerifyTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Token); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
