// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/PRPO-skupina-02/common/clients/auth/models"
)

// VerifyTokenReader is a Reader for the VerifyToken structure.
type VerifyTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VerifyTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewVerifyTokenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewVerifyTokenBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewVerifyTokenUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewVerifyTokenInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /verify] VerifyToken", response, response.Code())
	}
}

// NewVerifyTokenOK creates a VerifyTokenOK with default headers values
func NewVerifyTokenOK() *VerifyTokenOK {
	return &VerifyTokenOK{}
}

/*
VerifyTokenOK describes a response with status code 200, with default header values.

OK
*/
type VerifyTokenOK struct {
	Payload *models.APIUserResponse
}

// IsSuccess returns true when this verify token o k response has a 2xx status code
func (o *VerifyTokenOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this verify token o k response has a 3xx status code
func (o *VerifyTokenOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this verify token o k response has a 4xx status code
func (o *VerifyTokenOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this verify token o k response has a 5xx status code
func (o *VerifyTokenOK) IsServerError() bool {
	return false
}

// IsCode returns true when this verify token o k response a status code equal to that given
func (o *VerifyTokenOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the verify token o k response
func (o *VerifyTokenOK) Code() int {
	return 200
}

func (o *VerifyTokenOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /verify][%d] verifyTokenOK %s", 200, payload)
}

func (o *VerifyTokenOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /verify][%d] verifyTokenOK %s", 200, payload)
}

func (o *VerifyTokenOK) GetPayload() *models.APIUserResponse {
	return o.Payload
}

func (o *VerifyTokenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIUserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewVerifyTokenBadRequest creates a VerifyTokenBadRequest with default headers values
func NewVerifyTokenBadRequest() *VerifyTokenBadRequest {
	return &VerifyTokenBadRequest{}
}

/*
VerifyTokenBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type VerifyTokenBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this verify token bad request response has a 2xx status code
func (o *VerifyTokenBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this verify token bad request response has a 3xx status code
func (o *VerifyTokenBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this verify token bad request response has a 4xx status code
func (o *VerifyTokenBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this verify token bad request response has a 5xx status code
func (o *VerifyTokenBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this verify token bad request response a status code equal to that given
func (o *VerifyTokenBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the verify token bad request response
func (o *VerifyTokenBadRequest) Code() int {
	return 400
}

func (o *VerifyTokenBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /verify][%d] verifyTokenBadRequest %s", 400, payload)
}

func (o *VerifyTokenBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /verify][%d] verifyTokenBadRequest %s", 400, payload)
}

func (o *VerifyTokenBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *VerifyTokenBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewVerifyTokenUnauthorized creates a VerifyTokenUnauthorized with default headers values
func NewVerifyTokenUnauthorized() *VerifyTokenUnauthorized {
	return &VerifyTokenUnauthorized{}
}

/*
VerifyTokenUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type VerifyTokenUnauthorized struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this verify token unauthorized response has a 2xx status code
func (o *VerifyTokenUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this verify token unauthorized response has a 3xx status code
func (o *VerifyTokenUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this verify token unauthorized response has a 4xx status code
func (o *VerifyTokenUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this verify token unauthorized response has a 5xx status code
func (o *VerifyTokenUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this verify token unauthorized response a status code equal to that given
func (o *VerifyTokenUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the verify token unauthorized response
func (o *VerifyTokenUnauthorized) Code() int {
	return 401
}

func (o *VerifyTokenUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /verify][%d] verifyTokenUnauthorized %s", 401, payload)
}

func (o *VerifyTokenUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /verify][%d] verifyTokenUnauthorized %s", 401, payload)
}

func (o *VerifyTokenUnauthorized) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *VerifyTokenUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewVerifyTokenInternalServerError creates a VerifyTokenInternalServerError with default headers values
func NewVerifyTokenInternalServerError() *VerifyTokenInternalServerError {
	return &VerifyTokenInternalServerError{}
}

/*
VerifyTokenInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type VerifyTokenInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this verify token internal server error response has a 2xx status code
func (o *VerifyTokenInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this verify token internal server error response has a 3xx status code
func (o *VerifyTokenInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this verify token internal server error response has a 4xx status code
func (o *VerifyTokenInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this verify token internal server error response has a 5xx status code
func (o *VerifyTokenInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this verify token internal server error response a status code equal to that given
func (o *VerifyTokenInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the verify token internal server error response
func (o *VerifyTokenInternalServerError) Code() int {
	return 500
}

func (o *VerifyTokenInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /verify][%d] verifyTokenInternalServerError %s", 500, payload)
}

func (o *VerifyTokenInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /verify][%d] verifyTokenInternalServerError %s", 500, payload)
}

func (o *VerifyTokenInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *VerifyTokenInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
VerifyTokenBody verify token body
swagger:model VerifyTokenBody
*/
type VerifyTokenBody struct {

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this verify token body
func (o *VerifyTokenBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this verify token body based on context it is used
func (o *VerifyTokenBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *VerifyTokenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *VerifyTokenBody) UnmarshalBinary(b []byte) error {
	var res VerifyTokenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
