// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUsersShowParams creates a new UsersShowParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUsersShowParams() *UsersShowParams {
	return &UsersShowParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUsersShowParamsWithTimeout creates a new UsersShowParams object
// with the ability to set a timeout on a request.
func NewUsersShowParamsWithTimeout(timeout time.Duration) *UsersShowParams {
	return &UsersShowParams{
		timeout: timeout,
	}
}

// NewUsersShowParamsWithContext creates a new UsersShowParams object
// with the ability to set a context for a request.
func NewUsersShowParamsWithContext(ctx context.Context) *UsersShowParams {
	return &UsersShowParams{
		Context: ctx,
	}
}

// NewUsersShowParamsWithHTTPClient creates a new UsersShowParams object
// with the ability to set a custom HTTPClient for a request.
func NewUsersShowParamsWithHTTPClient(client *http.Client) *UsersShowParams {
	return &UsersShowParams{
		HTTPClient: client,
	}
}

/*
UsersShowParams contains all the parameters to send to the API endpoint

	for the users show operation.

	Typically these are written to a http.Request.
*/
type UsersShowParams struct {

	/* UserID.

	   User ID
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the users show params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UsersShowParams) WithDefaults() *UsersShowParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the users show params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UsersShowParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the users show params
func (o *UsersShowParams) WithTimeout(timeout time.Duration) *UsersShowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the users show params
func (o *UsersShowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the users show params
func (o *UsersShowParams) WithContext(ctx context.Context) *UsersShowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the users show params
func (o *UsersShowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the users show params
func (o *UsersShowParams) WithHTTPClient(client *http.Client) *UsersShowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the users show params
func (o *UsersShowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the users show params
func (o *UsersShowParams) WithUserID(userID string) *UsersShowParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the users show params
func (o *UsersShowParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *UsersShowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param userID
	if err := r.SetPathParam("userID", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
