// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/common/clients/auth/models"
)

// NewUsersUpdateParams creates a new UsersUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUsersUpdateParams() *UsersUpdateParams {
	return &UsersUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUsersUpdateParamsWithTimeout creates a new UsersUpdateParams object
// with the ability to set a timeout on a request.
func NewUsersUpdateParamsWithTimeout(timeout time.Duration) *UsersUpdateParams {
	return &UsersUpdateParams{
		timeout: timeout,
	}
}

// NewUsersUpdateParamsWithContext creates a new UsersUpdateParams object
// with the ability to set a context for a request.
func NewUsersUpdateParamsWithContext(ctx context.Context) *UsersUpdateParams {
	return &UsersUpdateParams{
		Context: ctx,
	}
}

// NewUsersUpdateParamsWithHTTPClient creates a new UsersUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewUsersUpdateParamsWithHTTPClient(client *http.Client) *UsersUpdateParams {
	return &UsersUpdateParams{
		HTTPClient: client,
	}
}

/*
UsersUpdateParams contains all the parameters to send to the API endpoint

	for the users update operation.

	Typically these are written to a http.Request.
*/
type UsersUpdateParams struct {

	/* Request.

	   User update details
	*/
	Request *models.APIAdminUpdateUserRequest

	/* UserID.

	   User ID
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the users update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UsersUpdateParams) WithDefaults() *UsersUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the users update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UsersUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the users update params
func (o *UsersUpdateParams) WithTimeout(timeout time.Duration) *UsersUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the users update params
func (o *UsersUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the users update params
func (o *UsersUpdateParams) WithContext(ctx context.Context) *UsersUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the users update params
func (o *UsersUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the users update params
func (o *UsersUpdateParams) WithHTTPClient(client *http.Client) *UsersUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the users update params
func (o *UsersUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the users update params
func (o *UsersUpdateParams) WithRequest(request *models.APIAdminUpdateUserRequest) *UsersUpdateParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the users update params
func (o *UsersUpdateParams) SetRequest(request *models.APIAdminUpdateUserRequest) {
	o.Request = request
}

// WithUserID adds the userID to the users update params
func (o *UsersUpdateParams) WithUserID(userID string) *UsersUpdateParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the users update params
func (o *UsersUpdateParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *UsersUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// path param userID
	if err := r.SetPathParam("userID", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
