// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/common/clients/auth/models"
)

// UsersShowReader is a Reader for the UsersShow structure.
type UsersShowReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UsersShowReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewUsersShowOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUsersShowBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUsersShowUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUsersShowNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUsersShowInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /users/{userID}] UsersShow", response, response.Code())
	}
}

// NewUsersShowOK creates a UsersShowOK with default headers values
func NewUsersShowOK() *UsersShowOK {
	return &UsersShowOK{}
}

/*
UsersShowOK describes a response with status code 200, with default header values.

OK
*/
type UsersShowOK struct {
	Payload *models.APIUserResponse
}

// IsSuccess returns true when this users show o k response has a 2xx status code
func (o *UsersShowOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this users show o k response has a 3xx status code
func (o *UsersShowOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this users show o k response has a 4xx status code
func (o *UsersShowOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this users show o k response has a 5xx status code
func (o *UsersShowOK) IsServerError() bool {
	return false
}

// IsCode returns true when this users show o k response a status code equal to that given
func (o *UsersShowOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the users show o k response
func (o *UsersShowOK) Code() int {
	return 200
}

func (o *UsersShowOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/{userID}][%d] usersShowOK %s", 200, payload)
}

func (o *UsersShowOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/{userID}][%d] usersShowOK %s", 200, payload)
}

func (o *UsersShowOK) GetPayload() *models.APIUserResponse {
	return o.Payload
}

func (o *UsersShowOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIUserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUsersShowBadRequest creates a UsersShowBadRequest with default headers values
func NewUsersShowBadRequest() *UsersShowBadRequest {
	return &UsersShowBadRequest{}
}

/*
UsersShowBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type UsersShowBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this users show bad request response has a 2xx status code
func (o *UsersShowBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this users show bad request response has a 3xx status code
func (o *UsersShowBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this users show bad request response has a 4xx status code
func (o *UsersShowBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this users show bad request response has a 5xx status code
func (o *UsersShowBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this users show bad request response a status code equal to that given
func (o *UsersShowBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the users show bad request response
func (o *UsersShowBadRequest) Code() int {
	return 400
}

func (o *UsersShowBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/{userID}][%d] usersShowBadRequest %s", 400, payload)
}

func (o *UsersShowBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/{userID}][%d] usersShowBadRequest %s", 400, payload)
}

func (o *UsersShowBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *UsersShowBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUsersShowUnauthorized creates a UsersShowUnauthorized with default headers values
func NewUsersShowUnauthorized() *UsersShowUnauthorized {
	return &UsersShowUnauthorized{}
}

/*
UsersShowUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type UsersShowUnauthorized struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this users show unauthorized response has a 2xx status code
func (o *UsersShowUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this users show unauthorized response has a 3xx status code
func (o *UsersShowUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this users show unauthorized response has a 4xx status code
func (o *UsersShowUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this users show unauthorized response has a 5xx status code
func (o *UsersShowUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this users show unauthorized response a status code equal to that given
func (o *UsersShowUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the users show unauthorized response
func (o *UsersShowUnauthorized) Code() int {
	return 401
}

func (o *UsersShowUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/{userID}][%d] usersShowUnauthorized %s", 401, payload)
}

func (o *UsersShowUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/{userID}][%d] usersShowUnauthorized %s", 401, payload)
}

func (o *UsersShowUnauthorized) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *UsersShowUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUsersShowNotFound creates a UsersShowNotFound with default headers values
func NewUsersShowNotFound() *UsersShowNotFound {
	return &UsersShowNotFound{}
}

/*
UsersShowNotFound describes a response with status code 404, with default header values.

Not Found
*/
type UsersShowNotFound struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this users show not found response has a 2xx status code
func (o *UsersShowNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this users show not found response has a 3xx status code
func (o *UsersShowNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this users show not found response has a 4xx status code
func (o *UsersShowNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this users show not found response has a 5xx status code
func (o *UsersShowNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this users show not found response a status code equal to that given
func (o *UsersShowNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the users show not found response
func (o *UsersShowNotFound) Code() int {
	return 404
}

func (o *UsersShowNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/{userID}][%d] usersShowNotFound %s", 404, payload)
}

func (o *UsersShowNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/{userID}][%d] usersShowNotFound %s", 404, payload)
}

func (o *UsersShowNotFound) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *UsersShowNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUsersShowInternalServerError creates a UsersShowInternalServerError with default headers values
func NewUsersShowInternalServerError() *UsersShowInternalServerError {
	return &UsersShowInternalServerError{}
}

/*
UsersShowInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type UsersShowInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this users show internal server error response has a 2xx status code
func (o *UsersShowInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this users show internal server error response has a 3xx status code
func (o *UsersShowInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this users show internal server error response has a 4xx status code
func (o *UsersShowInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this users show internal server error response has a 5xx status code
func (o *UsersShowInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this users show internal server error response a status code equal to that given
func (o *UsersShowInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the users show internal server error response
func (o *UsersShowInternalServerError) Code() int {
	return 500
}

func (o *UsersShowInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/{userID}][%d] usersShowInternalServerError %s", 500, payload)
}

func (o *UsersShowInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/{userID}][%d] usersShowInternalServerError %s", 500, payload)
}

func (o *UsersShowInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *UsersShowInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
