// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/common/clients/auth/models"
)

// UsersListReader is a Reader for the UsersList structure.
type UsersListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UsersListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewUsersListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUsersListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUsersListUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUsersListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /users] UsersList", response, response.Code())
	}
}

// NewUsersListOK creates a UsersListOK with default headers values
func NewUsersListOK() *UsersListOK {
	return &UsersListOK{}
}

/*
UsersListOK describes a response with status code 200, with default header values.

OK
*/
type UsersListOK struct {
	Payload []*models.APIUserResponse
}

// IsSuccess returns true when this users list o k response has a 2xx status code
func (o *UsersListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this users list o k response has a 3xx status code
func (o *UsersListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this users list o k response has a 4xx status code
func (o *UsersListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this users list o k response has a 5xx status code
func (o *UsersListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this users list o k response a status code equal to that given
func (o *UsersListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the users list o k response
func (o *UsersListOK) Code() int {
	return 200
}

func (o *UsersListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users][%d] usersListOK %s", 200, payload)
}

func (o *UsersListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users][%d] usersListOK %s", 200, payload)
}

func (o *UsersListOK) GetPayload() []*models.APIUserResponse {
	return o.Payload
}

func (o *UsersListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUsersListBadRequest creates a UsersListBadRequest with default headers values
func NewUsersListBadRequest() *UsersListBadRequest {
	return &UsersListBadRequest{}
}

/*
UsersListBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type UsersListBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this users list bad request response has a 2xx status code
func (o *UsersListBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this users list bad request response has a 3xx status code
func (o *UsersListBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this users list bad request response has a 4xx status code
func (o *UsersListBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this users list bad request response has a 5xx status code
func (o *UsersListBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this users list bad request response a status code equal to that given
func (o *UsersListBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the users list bad request response
func (o *UsersListBadRequest) Code() int {
	return 400
}

func (o *UsersListBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users][%d] usersListBadRequest %s", 400, payload)
}

func (o *UsersListBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users][%d] usersListBadRequest %s", 400, payload)
}

func (o *UsersListBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *UsersListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUsersListUnauthorized creates a UsersListUnauthorized with default headers values
func NewUsersListUnauthorized() *UsersListUnauthorized {
	return &UsersListUnauthorized{}
}

/*
UsersListUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type UsersListUnauthorized struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this users list unauthorized response has a 2xx status code
func (o *UsersListUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this users list unauthorized response has a 3xx status code
func (o *UsersListUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this users list unauthorized response has a 4xx status code
func (o *UsersListUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this users list unauthorized response has a 5xx status code
func (o *UsersListUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this users list unauthorized response a status code equal to that given
func (o *UsersListUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the users list unauthorized response
func (o *UsersListUnauthorized) Code() int {
	return 401
}

func (o *UsersListUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users][%d] usersListUnauthorized %s", 401, payload)
}

func (o *UsersListUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users][%d] usersListUnauthorized %s", 401, payload)
}

func (o *UsersListUnauthorized) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *UsersListUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUsersListInternalServerError creates a UsersListInternalServerError with default headers values
func NewUsersListInternalServerError() *UsersListInternalServerError {
	return &UsersListInternalServerError{}
}

/*
UsersListInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type UsersListInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this users list internal server error response has a 2xx status code
func (o *UsersListInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this users list internal server error response has a 3xx status code
func (o *UsersListInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this users list internal server error response has a 4xx status code
func (o *UsersListInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this users list internal server error response has a 5xx status code
func (o *UsersListInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this users list internal server error response a status code equal to that given
func (o *UsersListInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the users list internal server error response
func (o *UsersListInternalServerError) Code() int {
	return 500
}

func (o *UsersListInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users][%d] usersListInternalServerError %s", 500, payload)
}

func (o *UsersListInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users][%d] usersListInternalServerError %s", 500, payload)
}

func (o *UsersListInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *UsersListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
