// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PRPO-skupina-02/common/clients/auth/models"
)

// UsersUpdateReader is a Reader for the UsersUpdate structure.
type UsersUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UsersUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewUsersUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUsersUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUsersUpdateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUsersUpdateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUsersUpdateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /users/{userID}] UsersUpdate", response, response.Code())
	}
}

// NewUsersUpdateOK creates a UsersUpdateOK with default headers values
func NewUsersUpdateOK() *UsersUpdateOK {
	return &UsersUpdateOK{}
}

/*
UsersUpdateOK describes a response with status code 200, with default header values.

OK
*/
type UsersUpdateOK struct {
	Payload *models.APIUserResponse
}

// IsSuccess returns true when this users update o k response has a 2xx status code
func (o *UsersUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this users update o k response has a 3xx status code
func (o *UsersUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this users update o k response has a 4xx status code
func (o *UsersUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this users update o k response has a 5xx status code
func (o *UsersUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this users update o k response a status code equal to that given
func (o *UsersUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the users update o k response
func (o *UsersUpdateOK) Code() int {
	return 200
}

func (o *UsersUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /users/{userID}][%d] usersUpdateOK %s", 200, payload)
}

func (o *UsersUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /users/{userID}][%d] usersUpdateOK %s", 200, payload)
}

func (o *UsersUpdateOK) GetPayload() *models.APIUserResponse {
	return o.Payload
}

func (o *UsersUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIUserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUsersUpdateBadRequest creates a UsersUpdateBadRequest with default headers values
func NewUsersUpdateBadRequest() *UsersUpdateBadRequest {
	return &UsersUpdateBadRequest{}
}

/*
UsersUpdateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type UsersUpdateBadRequest struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this users update bad request response has a 2xx status code
func (o *UsersUpdateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this users update bad request response has a 3xx status code
func (o *UsersUpdateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this users update bad request response has a 4xx status code
func (o *UsersUpdateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this users update bad request response has a 5xx status code
func (o *UsersUpdateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this users update bad request response a status code equal to that given
func (o *UsersUpdateBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the users update bad request response
func (o *UsersUpdateBadRequest) Code() int {
	return 400
}

func (o *UsersUpdateBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /users/{userID}][%d] usersUpdateBadRequest %s", 400, payload)
}

func (o *UsersUpdateBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /users/{userID}][%d] usersUpdateBadRequest %s", 400, payload)
}

func (o *UsersUpdateBadRequest) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *UsersUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUsersUpdateUnauthorized creates a UsersUpdateUnauthorized with default headers values
func NewUsersUpdateUnauthorized() *UsersUpdateUnauthorized {
	return &UsersUpdateUnauthorized{}
}

/*
UsersUpdateUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type UsersUpdateUnauthorized struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this users update unauthorized response has a 2xx status code
func (o *UsersUpdateUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this users update unauthorized response has a 3xx status code
func (o *UsersUpdateUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this users update unauthorized response has a 4xx status code
func (o *UsersUpdateUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this users update unauthorized response has a 5xx status code
func (o *UsersUpdateUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this users update unauthorized response a status code equal to that given
func (o *UsersUpdateUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the users update unauthorized response
func (o *UsersUpdateUnauthorized) Code() int {
	return 401
}

func (o *UsersUpdateUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /users/{userID}][%d] usersUpdateUnauthorized %s", 401, payload)
}

func (o *UsersUpdateUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /users/{userID}][%d] usersUpdateUnauthorized %s", 401, payload)
}

func (o *UsersUpdateUnauthorized) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *UsersUpdateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUsersUpdateNotFound creates a UsersUpdateNotFound with default headers values
func NewUsersUpdateNotFound() *UsersUpdateNotFound {
	return &UsersUpdateNotFound{}
}

/*
UsersUpdateNotFound describes a response with status code 404, with default header values.

Not Found
*/
type UsersUpdateNotFound struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this users update not found response has a 2xx status code
func (o *UsersUpdateNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this users update not found response has a 3xx status code
func (o *UsersUpdateNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this users update not found response has a 4xx status code
func (o *UsersUpdateNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this users update not found response has a 5xx status code
func (o *UsersUpdateNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this users update not found response a status code equal to that given
func (o *UsersUpdateNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the users update not found response
func (o *UsersUpdateNotFound) Code() int {
	return 404
}

func (o *UsersUpdateNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /users/{userID}][%d] usersUpdateNotFound %s", 404, payload)
}

func (o *UsersUpdateNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /users/{userID}][%d] usersUpdateNotFound %s", 404, payload)
}

func (o *UsersUpdateNotFound) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *UsersUpdateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUsersUpdateInternalServerError creates a UsersUpdateInternalServerError with default headers values
func NewUsersUpdateInternalServerError() *UsersUpdateInternalServerError {
	return &UsersUpdateInternalServerError{}
}

/*
UsersUpdateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type UsersUpdateInternalServerError struct {
	Payload *models.MiddlewareHTTPError
}

// IsSuccess returns true when this users update internal server error response has a 2xx status code
func (o *UsersUpdateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this users update internal server error response has a 3xx status code
func (o *UsersUpdateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this users update internal server error response has a 4xx status code
func (o *UsersUpdateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this users update internal server error response has a 5xx status code
func (o *UsersUpdateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this users update internal server error response a status code equal to that given
func (o *UsersUpdateInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the users update internal server error response
func (o *UsersUpdateInternalServerError) Code() int {
	return 500
}

func (o *UsersUpdateInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /users/{userID}][%d] usersUpdateInternalServerError %s", 500, payload)
}

func (o *UsersUpdateInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /users/{userID}][%d] usersUpdateInternalServerError %s", 500, payload)
}

func (o *UsersUpdateInternalServerError) GetPayload() *models.MiddlewareHTTPError {
	return o.Payload
}

func (o *UsersUpdateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MiddlewareHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
