// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewUsersListParams creates a new UsersListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUsersListParams() *UsersListParams {
	return &UsersListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUsersListParamsWithTimeout creates a new UsersListParams object
// with the ability to set a timeout on a request.
func NewUsersListParamsWithTimeout(timeout time.Duration) *UsersListParams {
	return &UsersListParams{
		timeout: timeout,
	}
}

// NewUsersListParamsWithContext creates a new UsersListParams object
// with the ability to set a context for a request.
func NewUsersListParamsWithContext(ctx context.Context) *UsersListParams {
	return &UsersListParams{
		Context: ctx,
	}
}

// NewUsersListParamsWithHTTPClient creates a new UsersListParams object
// with the ability to set a custom HTTPClient for a request.
func NewUsersListParamsWithHTTPClient(client *http.Client) *UsersListParams {
	return &UsersListParams{
		HTTPClient: client,
	}
}

/*
UsersListParams contains all the parameters to send to the API endpoint

	for the users list operation.

	Typically these are written to a http.Request.
*/
type UsersListParams struct {

	/* Limit.

	   Limit the number of responses

	   Default: 10
	*/
	Limit *int64

	/* Offset.

	   Offset the first response
	*/
	Offset *int64

	/* Sort.

	   Sort results
	*/
	Sort *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the users list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UsersListParams) WithDefaults() *UsersListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the users list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UsersListParams) SetDefaults() {
	var (
		limitDefault = int64(10)

		offsetDefault = int64(0)
	)

	val := UsersListParams{
		Limit:  &limitDefault,
		Offset: &offsetDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the users list params
func (o *UsersListParams) WithTimeout(timeout time.Duration) *UsersListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the users list params
func (o *UsersListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the users list params
func (o *UsersListParams) WithContext(ctx context.Context) *UsersListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the users list params
func (o *UsersListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the users list params
func (o *UsersListParams) WithHTTPClient(client *http.Client) *UsersListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the users list params
func (o *UsersListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the users list params
func (o *UsersListParams) WithLimit(limit *int64) *UsersListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the users list params
func (o *UsersListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the users list params
func (o *UsersListParams) WithOffset(offset *int64) *UsersListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the users list params
func (o *UsersListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithSort adds the sort to the users list params
func (o *UsersListParams) WithSort(sort *string) *UsersListParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the users list params
func (o *UsersListParams) SetSort(sort *string) {
	o.Sort = sort
}

// WriteToRequest writes these params to a swagger request
func (o *UsersListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.Sort != nil {

		// query param sort
		var qrSort string

		if o.Sort != nil {
			qrSort = *o.Sort
		}
		qSort := qrSort
		if qSort != "" {

			if err := r.SetQueryParam("sort", qSort); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
