// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIUpdateUserRequest api update user request
//
// swagger:model api.UpdateUserRequest
type APIUpdateUserRequest struct {

	// first name
	// Min Length: 1
	FirstName string `json:"first_name,omitempty"`

	// last name
	// Min Length: 1
	LastName string `json:"last_name,omitempty"`
}

// Validate validates this api update user request
func (m *APIUpdateUserRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFirstName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIUpdateUserRequest) validateFirstName(formats strfmt.Registry) error {
	if swag.IsZero(m.FirstName) { // not required
		return nil
	}

	if err := validate.MinLength("first_name", "body", m.FirstName, 1); err != nil {
		return err
	}

	return nil
}

func (m *APIUpdateUserRequest) validateLastName(formats strfmt.Registry) error {
	if swag.IsZero(m.LastName) { // not required
		return nil
	}

	if err := validate.MinLength("last_name", "body", m.LastName, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this api update user request based on context it is used
func (m *APIUpdateUserRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIUpdateUserRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIUpdateUserRequest) UnmarshalBinary(b []byte) error {
	var res APIUpdateUserRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
