// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APITokenResponse api token response
//
// swagger:model api.TokenResponse
type APITokenResponse struct {

	// access token
	AccessToken string `json:"access_token,omitempty"`

	// seconds
	ExpiresIn int64 `json:"expires_in,omitempty"`

	// refresh token
	RefreshToken string `json:"refresh_token,omitempty"`
}

// Validate validates this api token response
func (m *APITokenResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api token response based on context it is used
func (m *APITokenResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APITokenResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APITokenResponse) UnmarshalBinary(b []byte) error {
	var res APITokenResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
