// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIAdminCreateUserRequest api admin create user request
//
// swagger:model api.AdminCreateUserRequest
type APIAdminCreateUserRequest struct {

	// active
	Active bool `json:"active,omitempty"`

	// email
	// Required: true
	Email *string `json:"email"`

	// first name
	// Min Length: 1
	FirstName string `json:"first_name,omitempty"`

	// last name
	// Min Length: 1
	LastName string `json:"last_name,omitempty"`

	// password
	// Required: true
	// Min Length: 8
	Password *string `json:"password"`

	// role
	// Required: true
	// Enum: ["customer","employee","admin"]
	Role *string `json:"role"`
}

// Validate validates this api admin create user request
func (m *APIAdminCreateUserRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFirstName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRole(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIAdminCreateUserRequest) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("email", "body", m.Email); err != nil {
		return err
	}

	return nil
}

func (m *APIAdminCreateUserRequest) validateFirstName(formats strfmt.Registry) error {
	if swag.IsZero(m.FirstName) { // not required
		return nil
	}

	if err := validate.MinLength("first_name", "body", m.FirstName, 1); err != nil {
		return err
	}

	return nil
}

func (m *APIAdminCreateUserRequest) validateLastName(formats strfmt.Registry) error {
	if swag.IsZero(m.LastName) { // not required
		return nil
	}

	if err := validate.MinLength("last_name", "body", m.LastName, 1); err != nil {
		return err
	}

	return nil
}

func (m *APIAdminCreateUserRequest) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	if err := validate.MinLength("password", "body", *m.Password, 8); err != nil {
		return err
	}

	return nil
}

var apiAdminCreateUserRequestTypeRolePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["customer","employee","admin"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		apiAdminCreateUserRequestTypeRolePropEnum = append(apiAdminCreateUserRequestTypeRolePropEnum, v)
	}
}

const (

	// APIAdminCreateUserRequestRoleCustomer captures enum value "customer"
	APIAdminCreateUserRequestRoleCustomer string = "customer"

	// APIAdminCreateUserRequestRoleEmployee captures enum value "employee"
	APIAdminCreateUserRequestRoleEmployee string = "employee"

	// APIAdminCreateUserRequestRoleAdmin captures enum value "admin"
	APIAdminCreateUserRequestRoleAdmin string = "admin"
)

// prop value enum
func (m *APIAdminCreateUserRequest) validateRoleEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, apiAdminCreateUserRequestTypeRolePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *APIAdminCreateUserRequest) validateRole(formats strfmt.Registry) error {

	if err := validate.Required("role", "body", m.Role); err != nil {
		return err
	}

	// value enum
	if err := m.validateRoleEnum("role", "body", *m.Role); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this api admin create user request based on context it is used
func (m *APIAdminCreateUserRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIAdminCreateUserRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIAdminCreateUserRequest) UnmarshalBinary(b []byte) error {
	var res APIAdminCreateUserRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
