// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIChangePasswordRequest api change password request
//
// swagger:model api.ChangePasswordRequest
type APIChangePasswordRequest struct {

	// new password
	// Required: true
	// Min Length: 8
	NewPassword *string `json:"new_password"`

	// old password
	// Required: true
	OldPassword *string `json:"old_password"`
}

// Validate validates this api change password request
func (m *APIChangePasswordRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNewPassword(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOldPassword(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIChangePasswordRequest) validateNewPassword(formats strfmt.Registry) error {

	if err := validate.Required("new_password", "body", m.NewPassword); err != nil {
		return err
	}

	if err := validate.MinLength("new_password", "body", *m.NewPassword, 8); err != nil {
		return err
	}

	return nil
}

func (m *APIChangePasswordRequest) validateOldPassword(formats strfmt.Registry) error {

	if err := validate.Required("old_password", "body", m.OldPassword); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this api change password request based on context it is used
func (m *APIChangePasswordRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIChangePasswordRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIChangePasswordRequest) UnmarshalBinary(b []byte) error {
	var res APIChangePasswordRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
