// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ModelsUserRole models user role
//
// swagger:model models.UserRole
type ModelsUserRole string

func NewModelsUserRole(value ModelsUserRole) *ModelsUserRole {
	return &value
}

// Pointer returns a pointer to a freshly-allocated ModelsUserRole.
func (m ModelsUserRole) Pointer() *ModelsUserRole {
	return &m
}

const (

	// ModelsUserRoleCustomer captures enum value "customer"
	ModelsUserRoleCustomer ModelsUserRole = "customer"

	// ModelsUserRoleEmployee captures enum value "employee"
	ModelsUserRoleEmployee ModelsUserRole = "employee"

	// ModelsUserRoleAdmin captures enum value "admin"
	ModelsUserRoleAdmin ModelsUserRole = "admin"
)

// for schema
var modelsUserRoleEnum []any

func init() {
	var res []ModelsUserRole
	if err := json.Unmarshal([]byte(`["customer","employee","admin"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		modelsUserRoleEnum = append(modelsUserRoleEnum, v)
	}
}

func (m ModelsUserRole) validateModelsUserRoleEnum(path, location string, value ModelsUserRole) error {
	if err := validate.EnumCase(path, location, value, modelsUserRoleEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this models user role
func (m ModelsUserRole) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateModelsUserRoleEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this models user role based on context it is used
func (m ModelsUserRole) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
